name: wifi_sensing
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - numpy=1.21.5
  - scipy=1.7.3
  - pandas=1.4.2
  - scikit-learn=1.0.2
  - matplotlib=3.5.2
  - seaborn=0.12.2
  - tqdm=4.64.0
  - pyyaml=6.0
  - tensorboard=2.9.1
  - pip
  - pip:
    - pywavelets==1.3.0
    - einops==0.6.1
